version: 2

models:
  - name: mart_product_category_performance
    description: Performance de vendas por categoria de produto
    columns:
      - name: product_category_name
        tests: [not_null]

      - name: receita_categoria
        tests:
          - dbt_utils.expression_is_true:
              arguments:
                expression: ">= 0"
